const mongoose = require('mongoose');

const MONGODB_URI = "mongodb://localhost:27017/jushi-agent";

async function main() {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    const db = mongoose.connection.db;

    // Find recent session
    const sessions = await db.collection('chat_sessions')
        .find({})
        .sort({ updatedAt: -1 })
        .limit(1)
        .toArray();

    if (sessions.length === 0) {
        console.log('No sessions found. Please start a conversation in the UI first.');
        process.exit(0);
    }

    const session = sessions[0];
    const sessionId = session._id.toString();
    console.log(`Using session: ${sessionId} - ${session.title}`);

    // Sample data simulating what the agent would produce
    const decompositionPayload = {
        project_name: "Persistence Verification",
        start_date: new Date().toISOString().split('T')[0],
        total_days: 1,
        tasks: [
            {
                title: "Verification Step 1",
                duration_hours: 1,
                description: "Reload the page and check if this component is visible."
            },
            {
                title: "Verification Step 2",
                duration_hours: 1,
                description: "Confirm that interactive state is preserved."
            }
        ],
        analysis: "Generated by verification script."
    };

    const messageDoc = {
        sessionId: sessionId,
        role: 'assistant',
        content: "I have generated a test plan to verify persistence. Please reload the page. If you see the plan below, it worked!",
        timestamp: new Date(),
        taskDecomposition: decompositionPayload
    };

    const result = await db.collection('chat_messages').insertOne(messageDoc);
    console.log(`Inserted test message with ID: ${result.insertedId}`);

    // Update session preview
    await db.collection('chat_sessions').updateOne(
        { _id: session._id },
        {
            $set: {
                updatedAt: new Date(),
                preview: "I have generated a test plan..."
            }
        }
    );

    await mongoose.disconnect();
}

main().catch(console.error);
